import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CURSOR_SVG =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='18' height='24' viewBox='-4 -4 18 20'%3E%3Cg transform='rotate(12 4.5 6)'%3E%3Cpath fill='black' fill-rule='evenodd' d='M0 0v11.188L2.969 8.322 3.129 8.183H8.165L0 0Z'/%3E%3C/g%3E%3C/svg%3E";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} style={{ cursor: `url(${CURSOR_SVG}) 5 4, auto` }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ cursor: `url(${CURSOR_SVG}) 5 4, auto` }}
      >
        {children}
      </body>
    </html>
  );
}
